### PR TITLE
Enforce `sh:maxCount` in forms

### LINKED ISSUE #195: `sh:maxCount` is not enforced in forms
### Description

Any `sh:maxCount` values are not enforced in the auto-generated forms. 
As a result, it is possible to add more items to a form than are actually allowed by the schema.

### Expected result

I would expect the number of items that can be added to the form to be limited to the `sh:maxCount` value.

### How to reproduce

As a contrived example, we can set `sh:maxCount 2` for the `publisher` field in the default `Resource` schema:

```turtle
... 
], [
    sh:path dct:publisher ;
    sh:node :AgentShape ;
    sh:minCount 1 ;
    sh:maxCount 2;
    dash:editor dash:BlankNodeEditor ;
    sh:order 3 ;
  ], [
...
```
In the resulting form we can add *more* than `2` publishers:

Image

### LINKED ISSUE #202: SHACL properties without min/maxCount do not have their editors shown
Using client `v1.17.1-rc.3`. The form when creating a new metadata instance:

Image

The shapes:

Image

Without diving deeper, I can see that homepage has a maxcount, while spatial and haspart do not.

### PR DESCRIPTION
**Pull request by dennisvang**
Hide the "Add" button if `sh:maxCount` has been reached.

For example, with `sh:maxCount 2` in the schema, the "Add" button is visible as long as there are fewer than `2` items: 

image

but it is hidden if there are `2`

image

The "Add" button becomes visible again if we remove one or more items using the "x" (remove) buttons.

fixes #195 
fixes #202

### CODE REVIEW

File: src/components/ShaclForm/FormRenderer.vue [hunk 1]
```diff
@@ -170,6 +171,11 @@ export default class FormRenderer extends Vue {
     return this.isList(field) && values > minCount
   }
 
+  canAddValue(field) {
+    const maxCount: number = _.get(field, 'maxCount', 0)
+    return maxCount === 0 || this.data[field.path].length < maxCount
```
Comment (MarekSuchanek) [inline src/components/ShaclForm/FormRenderer.vue]: Max count 0 has special meaning (not that it would make sense otherwise)? Just wondering, otherwise it could be just the second part after `||`

**Review by MarekSuchanek — APPROVED** [review]

File: src/components/ShaclForm/FormRenderer.vue (hunk 1 above)
Comment (dennisvang) [reply src/components/ShaclForm/FormRenderer.vue]: >Max count 0 has special meaning (not that it would make sense otherwise)?

@MarekSuchanek That's a good question. In my implementation above, `maxCount 0` implies that `maxCount` is not defined in the schema, assuming that `maxCount 0` would never occur in a real schema. 

I assumed this because it aligns with the existing behavior of the client for `maxCount 0`, based on `isList()`:

https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/d6eacb9d71c9966d8ab1311c47999c18b5f5f1ed/src/components/ShaclForm/fieldUtils.ts#L24-L26

and also on `getShaclValue()`:

https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/d6eacb9d71c9966d8ab1311c47999c18b5f5f1ed/src/utils/metadata.ts#L95

However, I'm not sure if this *is* a valid assumption, as there may be use cases where it is necessary to explicitly forbid the use of a property by setting `maxCount 0`...

>Just wondering, otherwise it could be just the second part after ||

I think we would at least need to check if `maxCount` is defined and not `null`.

What do you think?

Comment (dennisvang) [reply src/components/ShaclForm/FormRenderer.vue]: @MarekSuchanek my implementation above actually gives rise to #202 because I forgot that lodash `get()` returns the default only when the attribute is `undefined`, but not if it is `null`.

So probably we should just set the default to `null` and test for `null`:

```typescript
canAddValue(field) {
    const maxCount: number | null = _.get(field, 'maxCount', null)
    return maxCount === null || this.data[field.path].length < maxCount
}
```

In addition, I wonder why `isList()` is defined the way it is (`field.maxCount !== 1`). Shouldn't it be something like the following?

```typescript
 function isList(field: FormField): boolean { 
   return field.maxCount === null || field.maxCount > 1 
 } 
```

And to show it can be `null`:

https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/d6eacb9d71c9966d8ab1311c47999c18b5f5f1ed/src/components/ShaclForm/Parser/SHACLParser.ts#L61

Comment (MarekSuchanek) [reply src/components/ShaclForm/FormRenderer.vue]: Agree, that sounds more error prone if `null` means infinity (any count) 👍🏻

Comment (dennisvang) [reply src/components/ShaclForm/FormRenderer.vue]: Thanks @MarekSuchanek . I verified the expected `isList()` behavior with Luiz and opened #205 accordingly.
