### PR TITLE
Fix removal of blank nodes

### LINKED ISSUE #200: Cannot remove existing blank node
### Description

If we remove an existing blank node value in (client v1.17.0 or develop), we get a validation error.

See example below.

### How to reproduce

1. Run a minimal fdp stack, e.g. in docker, using fdp v1.17.4 and fdp-client v1.17.0
2. Edit the default `Resource` schema and remove the `sh:maxCount` line for the `publisher`, to allow multiple publishers, and "Save and release" this schema.
    (This makes little sense, but it is just an easy way to reproduce the issue.)
3. create a new Catalog with *two* or more publishers, and save this catalog 

   Image

4. edit the newly created catalog to remove one of the publishers (by clicking the cross)
5. click "View RDF" to observe that one of the publishers has indeed been removed, but that the following line has been added at the bottom: 
   ```turtle
   [ a foaf:Agent ].
   ```
6. click "Save" to observe the following validation error:

   ```turtle
   [] a sh:ValidationReport;
     sh:conforms false;
     rdf4j:truncated false;
     sh:result [ a sh:ValidationResult;
         sh:focusNode [];
         rsx:shapesGraph rdf4j:SHACLShapeGraph;
         sh:resultPath foaf:name;
         sh:sourceConstraintComponent sh:MinCountConstraintComponent;
         sh:resultSeverity sh:Violation;
         sh:sourceShape [ a sh:PropertyShape;
             sh:path foaf:name;
             sh:minCount 1
           ]
       ] .
   ```

### PR DESCRIPTION
**Pull request by dennisvang**
From the code, I inferred that the `clear()` function in `formData.ts` is supposed to remove all RDF statements related to the fields rendered in the HTML form from the in-memory RDF store.

These statements are reconstructed later, in `createQuads()`, based on the form data.

However, the `clear()` function failed to remove the blank node *type* statements, because these are not included in `field.nodeshape.fields` (instead, they are found in `field.nodeshape.targetClasses`). So we were left with orphaned statements like `[ a foaf:Agent ].` as described in #200.

To fix this, I added the line `store.removeMany(statement.object)`, which (afaik) actually removes all statements related to the blank node, including the type statement. The recursive call to `clear()` is still necessary to cover the case of nested blank nodes.

This fixed the removal of the blank node, so we did not see the orphaned type statements anymore (`[ a foaf:Agent ].`). However, `createQuads()` subsequently failed to restore these *type* statements when processing the form data.

I assumed this was caused by the fact that `createQuads()` used the original RDF store (`rdf`) for reference, instead of the updated RDF store (`store`), so I changed that as well.

fixes #200

### CODE REVIEW

File: src/components/ShaclForm/formData.ts [hunk 1]
```diff
@@ -148,22 +148,43 @@ export function toRdf(
...
       store.removeMany(subject, $rdf.namedNode(field.path))
     })
   }
+
+  // Remove all existing statements related to the present shape from the RDF store
   clear($rdf.namedNode(subjectStr), shape.fields)
 
-  store.addAll(createQuads(data, rdf, shape))
+  // Create new statements from form data, and add them to the RDF store
+  store.addAll(createQuads(data, store, shape))
```
Comment (MarekSuchanek) [inline src/components/ShaclForm/formData.ts:187]: `rdf` changed here to `store` but then `serializer` uses `rdf` still?  and in the end `store` statements are serialized... really don't understand this part, sorry

Comment (dennisvang) [reply src/components/ShaclForm/formData.ts:187]: Hi @MarekSuchanek thanks for taking a look at this.

I changed `rdf` to `store` in the call to `createQuads()` because, as far as I can see, that function needs access to the *modified* store (`store`), instead of the original *unmodified* one from the response (`rdf`). I think this is in line with the [previous implementation], where the original `rdf` argument *was* modified.

The `createQuads()` function only uses this store (the `originalRdf` argument) to determine whether to add RDF type statements:

https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/39e56f56fc5a76c397ac4574b8a988c9c72cee46/src/components/ShaclForm/formData.ts#L83-L86

So, if `originalRdf` equals `rdf`, i.e. the original *unmodified* rdf store from the response, `createQuads` will never recreate type statements, even if they have been removed from the copied `store` in the [clear()] call.

Actually I wonder if the `filter` in `createQuads()` L85 is even still necessary now that `clear()` removes everything properly...

As for the serializer part... I did not touch that. 

It is indeed strange that the [Serializer] is instantiated with `rdf` 

https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/39e56f56fc5a76c397ac4574b8a988c9c72cee46/src/components/ShaclForm/formData.ts#L169

only to add statements from the `store` in the end

https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/39e56f56fc5a76c397ac4574b8a988c9c72cee46/src/components/ShaclForm/formData.ts#L177-L178

Although I would expect the `Serializer` to be instantiated with `store` as well, instead of `rdf`, it has been like this since 2020 and appears to work.

Also not sure why the serialization is done this way instead of using e.g. [$rdf.serialize()]. 
(actually it turns out that *was* used in the [previous implementation])

Unfortunately, the rdflib.js docs are not very helpful here... 

[Serializer]: https://linkeddata.github.io/rdflib.js/doc/functions/Serializer.html
[$rdf.serialize()]: https://linkeddata.github.io/rdflib.js/doc/functions/serialize.html
[clear()]: https://github.com/FAIRDataTeam/FAIRDataPoint-client/blob/39e56f56fc5a76c397ac4574b8a988c9c72cee46/src/components/ShaclForm/formData.ts#L164
[previous implementation]: https://github.com/FAIRDataTeam/FAIRDataPoint-client/blame/3e27dbb02ead5fff91397d909d214fba9eca18e2/src/components/ShaclForm/formData.ts

Comment (MarekSuchanek) [reply src/components/ShaclForm/formData.ts:187]: OK, sounds good... unfortunately, cannot help much with this. Maybe custom serialization has been done because of requirement on "nice" prefixes and this `sir` flag on serializer (https://github.com/FAIRDataTeam/FAIRDataPoint-client/commit/98952cb9d82c7379be2503d2fc3d559a81873dde#diff-ef3921a4436ad0844211507355b994db998926fe0693538d6972c9711ab8a71aR87)?

rdflib.js docs are and always were a big pain, but that is the case for most of RDF libraries in many languages for some reason 😞

**Review by MarekSuchanek — APPROVED** [review]
